[build]
publish = "public"  # default hugo build folder
command = "echo 'Deploy prebuilt public only'" # hugo build command

[context.production.environment]
HUGO_VERSION = "0.62.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
HUGO_BASEURL = "/"